# Generated by Django 4.0.3 on 2022-04-03 04:31

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('craigslist_app', '0002_post_price_currency_alter_post_contact_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
